STRATEGY_REGISTRY = {
    "call_debit_spread": {
        "family": "directional_bullish",
        "view_tags": ["bullish", "trend_up", "moderate_vol"],
        "theta_profile": "negative",
        "vega_profile": "positive",
        "defined_risk": True,
        "execution_ready": True,
    },
    "put_debit_spread": {
        "family": "directional_bearish",
        "view_tags": ["bearish", "trend_down", "moderate_vol"],
        "theta_profile": "negative",
        "vega_profile": "positive",
        "defined_risk": True,
        "execution_ready": True,
    },
    "put_credit_spread": {
        "family": "bullish_income",
        "view_tags": ["bullish", "range_up", "vol_sell"],
        "theta_profile": "positive",
        "vega_profile": "negative",
        "defined_risk": True,
        "execution_ready": True,
    },

    # Registered now, execution later
    "bear_call_spread": {
        "family": "bearish_income",
        "view_tags": ["bearish", "range_down", "vol_sell"],
        "theta_profile": "positive",
        "vega_profile": "negative",
        "defined_risk": True,
        "execution_ready": False,
    },
    "iron_condor": {
        "family": "neutral_income",
        "view_tags": ["neutral", "range_bound", "vol_sell"],
        "theta_profile": "positive",
        "vega_profile": "negative",
        "defined_risk": True,
        "execution_ready": False,
    },
    "iron_butterfly": {
        "family": "neutral_income_high_conviction",
        "view_tags": ["neutral", "pinning", "vol_sell"],
        "theta_profile": "positive",
        "vega_profile": "negative",
        "defined_risk": True,
        "execution_ready": False,
    },
    "long_straddle": {
        "family": "long_vol",
        "view_tags": ["sharp_move", "event_risk", "vol_buy"],
        "theta_profile": "negative",
        "vega_profile": "positive",
        "defined_risk": True,
        "execution_ready": False,
    },
    "long_strangle": {
        "family": "long_vol",
        "view_tags": ["sharp_move", "event_risk", "vol_buy"],
        "theta_profile": "negative",
        "vega_profile": "positive",
        "defined_risk": True,
        "execution_ready": False,
    },
    "call_calendar": {
        "family": "bullish_calendar",
        "view_tags": ["bullish", "term_structure", "vol_shape"],
        "theta_profile": "mixed",
        "vega_profile": "positive",
        "defined_risk": True,
        "execution_ready": False,
    },
    "put_calendar": {
        "family": "bearish_calendar",
        "view_tags": ["bearish", "term_structure", "vol_shape"],
        "theta_profile": "mixed",
        "vega_profile": "positive",
        "defined_risk": True,
        "execution_ready": False,
    },
    "collar": {
        "family": "hedge",
        "view_tags": ["hedge_stock", "downside_protection"],
        "theta_profile": "mixed",
        "vega_profile": "mixed",
        "defined_risk": True,
        "execution_ready": False,
    },
    "protective_put": {
        "family": "hedge",
        "view_tags": ["hedge_stock", "downside_protection", "vol_buy"],
        "theta_profile": "negative",
        "vega_profile": "positive",
        "defined_risk": True,
        "execution_ready": False,
    },
    "covered_call": {
        "family": "income",
        "view_tags": ["produce_income", "mild_bullish", "vol_sell"],
        "theta_profile": "positive",
        "vega_profile": "negative",
        "defined_risk": False,
        "execution_ready": False,
    },
}
